---
- name: Fetch devices from NetBox and save to local HTML file
  hosts: localhost
  gather_facts: true
  collections:
    - ansible.builtin
  vars:
    netbox_url: "https://mnqh6527.cloud.netboxapp.com"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_file: "/home/user1/reports/devices.html"
    target_host: "node3"  # Replace with your target host

  tasks:
    - name: Ensure the /home/user1/reports directory exists on target host
      file:
        path: /home/user1/reports
        state: directory
        mode: '0755'
      delegate_to: "{{ target_host }}"

    - name: Fetch devices from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_response
      failed_when: netbox_response.status != 200

    - name: Debug NetBox devices response
      debug:
        var: netbox_response.json.results
      failed_when: netbox_response.json is not defined or netbox_response.json.results is not defined

    - name: Save NetBox devices to a JSON file
      copy:
        content: "{{ netbox_response.content }}"
        dest: "/tmp/netbox_devices.json"
        mode: '0644'
      failed_when: netbox_response.content is not defined

    - name: Ensure permanent directory exists on target host
      file:
        path: /home/user1/netbox_data
        state: directory
        mode: '0755'
      delegate_to: "{{ target_host }}"

    - name: Move JSON file to a permanent location on target host
      command: mv /tmp/netbox_devices.json /home/user1/netbox_data/netbox_devices.json
      failed_when: result.rc != 0
      register: result
      delegate_to: "{{ target_host }}"

    - name: Debug the devices variable before template
      debug:
        var: netbox_response.json.results

    - name: Convert NetBox devices JSON to HTML on target host
      template:
        src: templates/netbox_devices.html.j2
        dest: "{{ output_file }}"
      vars:
        devices: "{{ netbox_response.json.results }}"
      register: template_result
      failed_when: template_result is failed
      delegate_to: "{{ target_host }}"

    - name: Debug template result
      debug:
        var: template_result
